import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Home/Footer/Footer";
import ScrollToTop from "@/components/Helper/ScrollToTop";

const beVietnam = localFont({
  src: [
    {
      path: "./fonts/BeVietnamPro-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/BeVietnamPro-ExtraBold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-vietnam",
});

export const metadata: Metadata = {
  title: "Course HTShun",
  description: "Generated by HTShun",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={beVietnam.variable}>
      <body className={`antialiased`}>
        {children}
        <Footer />
        <ScrollToTop />
      </body>
    </html>
  );
}
